// Package gate provides tests for factorize metrics digest invariants.
package gate

import (
	"crypto/sha256"
	"encoding/hex"
	"testing"
)

func TestContentBoundDigest_DifferentContentProducesDifferentDigest(t *testing.T) {
	h1 := sha256.New()
	h1.Write([]byte("factorize-subject-v2"))
	h1.Write([]byte{0})
	h1.Write([]byte("abc123"))
	h1.Write([]byte{0})
	h1.Write([]byte("def456"))
	h1.Write([]byte{0})
	h1.Write([]byte("clean"))
	h1.Write([]byte{0})
	h1.Write([]byte("1"))
	h1.Write([]byte{0})
	h1.Write([]byte("file.txt"))
	h1.Write([]byte{0})
	h1.Write([]byte("exists"))
	h1.Write([]byte{0})
	h1.Write([]byte("100644"))
	h1.Write([]byte{0})
	h1.Write([]byte("sha256-of-content-a"))
	h1.Write([]byte{0})

	h2 := sha256.New()
	h2.Write([]byte("factorize-subject-v2"))
	h2.Write([]byte{0})
	h2.Write([]byte("abc123"))
	h2.Write([]byte{0})
	h2.Write([]byte("def456"))
	h2.Write([]byte{0})
	h2.Write([]byte("clean"))
	h2.Write([]byte{0})
	h2.Write([]byte("1"))
	h2.Write([]byte{0})
	h2.Write([]byte("file.txt"))
	h2.Write([]byte{0})
	h2.Write([]byte("exists"))
	h2.Write([]byte{0})
	h2.Write([]byte("100644"))
	h2.Write([]byte{0})
	h2.Write([]byte("sha256-of-content-b"))
	h2.Write([]byte{0})

	d1 := hex.EncodeToString(h1.Sum(nil))
	d2 := hex.EncodeToString(h2.Sum(nil))
	if d1 == d2 {
		t.Fatalf("different content should produce different digest")
	}
}

func TestContentBoundDigest_DifferentPathProducesDifferentDigest(t *testing.T) {
	h1 := sha256.New()
	h1.Write([]byte("factorize-subject-v2"))
	h1.Write([]byte{0})
	h1.Write([]byte("abc123"))
	h1.Write([]byte{0})
	h1.Write([]byte("def456"))
	h1.Write([]byte{0})
	h1.Write([]byte("clean"))
	h1.Write([]byte{0})
	h1.Write([]byte("1"))
	h1.Write([]byte{0})
	h1.Write([]byte("file-a.txt"))
	h1.Write([]byte{0})
	h1.Write([]byte("exists"))
	h1.Write([]byte{0})
	h1.Write([]byte("100644"))
	h1.Write([]byte{0})
	h1.Write([]byte("same-sha"))
	h1.Write([]byte{0})

	h2 := sha256.New()
	h2.Write([]byte("factorize-subject-v2"))
	h2.Write([]byte{0})
	h2.Write([]byte("abc123"))
	h2.Write([]byte{0})
	h2.Write([]byte("def456"))
	h2.Write([]byte{0})
	h2.Write([]byte("clean"))
	h2.Write([]byte{0})
	h2.Write([]byte("1"))
	h2.Write([]byte{0})
	h2.Write([]byte("file-b.txt"))
	h2.Write([]byte{0})
	h2.Write([]byte("exists"))
	h2.Write([]byte{0})
	h2.Write([]byte("100644"))
	h2.Write([]byte{0})
	h2.Write([]byte("same-sha"))
	h2.Write([]byte{0})

	d1 := hex.EncodeToString(h1.Sum(nil))
	d2 := hex.EncodeToString(h2.Sum(nil))
	if d1 == d2 {
		t.Fatalf("different paths should produce different digest")
	}
}

func TestContentBoundDigest_SameContentSameDigest(t *testing.T) {
	h1 := sha256.New()
	h1.Write([]byte("factorize-subject-v2"))
	h1.Write([]byte{0})
	h1.Write([]byte("abc123"))
	h1.Write([]byte{0})
	h1.Write([]byte("def456"))
	h1.Write([]byte{0})
	h1.Write([]byte("clean"))
	h1.Write([]byte{0})
	h1.Write([]byte("1"))
	h1.Write([]byte{0})
	h1.Write([]byte("file.txt"))
	h1.Write([]byte{0})
	h1.Write([]byte("exists"))
	h1.Write([]byte{0})
	h1.Write([]byte("100644"))
	h1.Write([]byte{0})
	h1.Write([]byte("same-sha"))
	h1.Write([]byte{0})

	h2 := sha256.New()
	h2.Write([]byte("factorize-subject-v2"))
	h2.Write([]byte{0})
	h2.Write([]byte("abc123"))
	h2.Write([]byte{0})
	h2.Write([]byte("def456"))
	h2.Write([]byte{0})
	h2.Write([]byte("clean"))
	h2.Write([]byte{0})
	h2.Write([]byte("1"))
	h2.Write([]byte{0})
	h2.Write([]byte("file.txt"))
	h2.Write([]byte{0})
	h2.Write([]byte("exists"))
	h2.Write([]byte{0})
	h2.Write([]byte("100644"))
	h2.Write([]byte{0})
	h2.Write([]byte("same-sha"))
	h2.Write([]byte{0})

	d1 := hex.EncodeToString(h1.Sum(nil))
	d2 := hex.EncodeToString(h2.Sum(nil))
	if d1 != d2 {
		t.Fatalf("same content should produce same digest")
	}
}
