package doctrinecompiler

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestIntegrationEndToEnd compiles an empty target, plans, verifies,
// and explains. It exercises the full happy path of every public
// entry point.
func TestIntegrationEndToEnd(t *testing.T) {
	withCompilerVersion(t, "0.1.0")
	pack, err := LoadCorePack()
	if err != nil {
		t.Fatalf("LoadCorePack: %v", err)
	}
	prof, err := pack.MustProfile(ProfileId("fsharp-elm-service-v1"))
	if err != nil {
		t.Fatalf("MustProfile: %v", err)
	}
	target := newEmptyTarget(t)
	plan, err := Plan(pack, prof, target)
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if len(plan.Actions) == 0 {
		t.Fatalf("Plan produced no actions")
	}
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("Compile: %v", err)
	}
	rep, err := Explain(pack, prof, target, "dev", "unknown", "unknown")
	if err != nil {
		t.Fatalf("Explain: %v", err)
	}
	if len(rep.Doctrines) == 0 {
		t.Errorf("Explain produced no doctrines")
	}
	result, err := Verify(pack, prof, target)
	if err != nil {
		t.Fatalf("Verify: %v", err)
	}
	if !result.OK {
		t.Errorf("Verify failed: %v", result.Findings)
	}
}

// TestIntegrationGoldenProjection is the headline integration test: it
// compiles an empty target and asserts every projected file matches
// the golden fixture byte-for-byte.
func TestIntegrationGoldenProjection(t *testing.T) {
	pack, err := LoadCorePack()
	if err != nil {
		t.Fatalf("LoadCorePack: %v", err)
	}
	prof, err := pack.MustProfile(ProfileId("fsharp-elm-service-v1"))
	if err != nil {
		t.Fatalf("MustProfile: %v", err)
	}
	target := newEmptyTarget(t)
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("Compile: %v", err)
	}
	gotTree := listTargetTree(t, target)
	wantTree := []string{
		".factory/doctrine.lock.json",
		".factory/generated/doctrine-inventory.md",
		".factory/generated/factory.mk",
		".factory/project.json",
		"Makefile",
		"docs/factory/README.md",
	}
	if !equalStringSet(gotTree, wantTree) {
		t.Fatalf("tree mismatch: got %v want %v", gotTree, wantTree)
	}
	for _, p := range wantTree {
		got := mustRead(t, filepath.Join(target, p))
		golden := mustRead(t, filepath.Join(expectedFixtureDir(t), p))
		if string(got) != string(golden) {
			t.Errorf("file %s differs from golden", p)
		}
	}
}

// TestIntegrationFixturesPresent asserts the canonical pack, profile,
// and golden fixture are present on disk.
func TestIntegrationFixturesPresent(t *testing.T) {
	files := []string{
		"packs/factory-core-v1/pack.json",
		"testdata/fsharp-elm-empty/expected/.factory/doctrine.lock.json",
		"testdata/fsharp-elm-empty/expected/.factory/project.json",
		"testdata/fsharp-elm-empty/expected/.factory/generated/factory.mk",
		"testdata/fsharp-elm-empty/expected/.factory/generated/doctrine-inventory.md",
		"testdata/fsharp-elm-empty/expected/Makefile",
		"testdata/fsharp-elm-empty/expected/docs/factory/README.md",
	}
	for _, f := range files {
		if _, err := os.Stat(f); err != nil {
			t.Errorf("missing fixture %s: %v", f, err)
		}
	}
}

// TestIntegrationIdempotent compiles twice and asserts the second
// run touches no bytes in the managed tree.
func TestIntegrationIdempotent(t *testing.T) {
	pack, err := LoadCorePack()
	if err != nil {
		t.Fatalf("LoadCorePack: %v", err)
	}
	prof, err := pack.MustProfile(ProfileId("fsharp-elm-service-v1"))
	if err != nil {
		t.Fatalf("MustProfile: %v", err)
	}
	target := newEmptyTarget(t)
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("Compile: %v", err)
	}
	before := make(map[string]string)
	for _, p := range listTargetTree(t, target) {
		before[p] = string(mustRead(t, filepath.Join(target, p)))
	}
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("Compile: %v", err)
	}
	for p, content := range before {
		got, err := os.ReadFile(filepath.Join(target, p))
		if err != nil {
			t.Errorf("file %s vanished: %v", p, err)
			continue
		}
		if string(got) != content {
			t.Errorf("file %s changed in idempotent compile", p)
		}
	}
}

// TestIntegrationNoticeOnManagedFiles ensures every managed output
// carries the documented "Generated by Leamas" notice.
func TestIntegrationNoticeOnManagedFiles(t *testing.T) {
	pack, err := LoadCorePack()
	if err != nil {
		t.Fatalf("LoadCorePack: %v", err)
	}
	prof, err := pack.MustProfile(ProfileId("fsharp-elm-service-v1"))
	if err != nil {
		t.Fatalf("MustProfile: %v", err)
	}
	target := newEmptyTarget(t)
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("Compile: %v", err)
	}
	managed := []string{
		".factory/generated/factory.mk",
		".factory/generated/doctrine-inventory.md",
		"docs/factory/README.md",
	}
	for _, p := range managed {
		data, err := os.ReadFile(filepath.Join(target, p))
		if err != nil {
			t.Fatalf("read %s: %v", p, err)
		}
		if !strings.Contains(string(data), "Generated by Leamas from factory-core-v1") {
			t.Errorf("missing generated notice in %s", p)
		}
		if !strings.Contains(string(data), "Do not edit this file directly") {
			t.Errorf("missing edit warning in %s", p)
		}
	}
}

// mustRead reads a file or fails the test.
func mustRead(t *testing.T, path string) []byte {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return data
}
