package doctrinecompiler

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestSeededOwnershipNotice verifies that newly seeded root Makefile files
// contain the seeded ownership notice instead of the managed "do not edit" warning.
func TestSeededOwnershipNotice(t *testing.T) {
	pack, err := LoadCorePack()
	if err != nil {
		t.Fatalf("LoadCorePack: %v", err)
	}
	prof, err := pack.MustProfile(ProfileId("fsharp-elm-service-v1"))
	if err != nil {
		t.Fatalf("MustProfile: %v", err)
	}
	target := newEmptyTarget(t)
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("Compile: %v", err)
	}

	mk := filepath.Join(target, "Makefile")
	data, err := os.ReadFile(mk)
	if err != nil {
		t.Fatalf("read Makefile: %v", err)
	}

	// Test 1: Seeded notice must be present.
	if !strings.Contains(string(data), "Seeded by Leamas from factory-core-v1") {
		t.Error("missing seeded notice in Makefile")
	}

	// Test 2: Seeded notice must contain "repository-owned after creation".
	if !strings.Contains(string(data), "repository-owned after creation") {
		t.Error("missing 'repository-owned after creation' in seeded Makefile header")
	}

	// Test 3: Seeded notice must NOT contain "Do not edit this file directly".
	if strings.Contains(string(data), "Do not edit this file directly") {
		t.Error("seeded Makefile contains managed-file 'do not edit' warning")
	}
}

// TestManagedFilesRetainManagedNotice verifies that managed files retain
// their existing "Generated by Leamas" and "Do not edit" warning.
func TestManagedFilesRetainManagedNotice(t *testing.T) {
	pack, err := LoadCorePack()
	if err != nil {
		t.Fatalf("LoadCorePack: %v", err)
	}
	prof, err := pack.MustProfile(ProfileId("fsharp-elm-service-v1"))
	if err != nil {
		t.Fatalf("MustProfile: %v", err)
	}
	target := newEmptyTarget(t)
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("Compile: %v", err)
	}

	managed := []string{
		".factory/generated/factory.mk",
		".factory/generated/doctrine-inventory.md",
		"docs/factory/README.md",
	}
	for _, p := range managed {
		data, err := os.ReadFile(filepath.Join(target, p))
		if err != nil {
			t.Fatalf("read %s: %v", p, err)
		}

		// Managed files must contain the generated notice.
		if !strings.Contains(string(data), "Generated by Leamas from factory-core-v1") {
			t.Errorf("missing generated notice in %s", p)
		}

		// Managed files must contain the do-not-edit warning.
		if !strings.Contains(string(data), "Do not edit this file directly") {
			t.Errorf("missing do-not-edit warning in %s", p)
		}

		// Managed files must NOT contain the seeded "repository-owned" notice.
		if strings.Contains(string(data), "repository-owned after creation") {
			t.Errorf("managed file %s contains seeded notice", p)
		}
	}
}

// TestSeededFilePreservationByteForByte verifies that recompilation does
// not overwrite an existing seeded Makefile and proves byte-for-byte equality.
func TestSeededFilePreservationByteForByte(t *testing.T) {
	pack, err := LoadCorePack()
	if err != nil {
		t.Fatalf("LoadCorePack: %v", err)
	}
	prof, err := pack.MustProfile(ProfileId("fsharp-elm-service-v1"))
	if err != nil {
		t.Fatalf("MustProfile: %v", err)
	}
	target := newEmptyTarget(t)

	// First compile creates the seeded Makefile.
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("first Compile: %v", err)
	}

	mk := filepath.Join(target, "Makefile")
	before, err := os.ReadFile(mk)
	if err != nil {
		t.Fatalf("read before: %v", err)
	}

	// Second compile must not modify the seeded file.
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("second Compile: %v", err)
	}

	after, err := os.ReadFile(mk)
	if err != nil {
		t.Fatalf("read after: %v", err)
	}

	// Byte-for-byte equality proof.
	if string(before) != string(after) {
		t.Errorf("seeded Makefile changed after recompilation:\nbefore:\n%s\nafter:\n%s", before, after)
	}
}

// TestSeededCustomTargetSurvivesRecompilation verifies that a repository-owned
// custom target added after initial compilation remains unchanged after recompilation.
func TestSeededCustomTargetSurvivesRecompilation(t *testing.T) {
	pack, err := LoadCorePack()
	if err != nil {
		t.Fatalf("LoadCorePack: %v", err)
	}
	prof, err := pack.MustProfile(ProfileId("fsharp-elm-service-v1"))
	if err != nil {
		t.Fatalf("MustProfile: %v", err)
	}
	target := newEmptyTarget(t)

	// First compile creates the seeded Makefile.
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("first Compile: %v", err)
	}

	mk := filepath.Join(target, "Makefile")

	// Add a repository-owned custom target.
	customContent := `# Seeded by Leamas from factory-core-v1.
# This file is repository-owned after creation.
# Preserve the required Factory integration contracts.

include .factory/generated/factory.mk

.PHONY: gate
gate: factorize

.PHONY: custom-target
custom-target:
	@echo "repository-owned custom target"
`
	if err := os.WriteFile(mk, []byte(customContent), 0o644); err != nil {
		t.Fatalf("write custom Makefile: %v", err)
	}

	// Recompilation must preserve the custom target.
	if _, err := Compile(pack, prof, target, CompilerOptions{}); err != nil {
		t.Fatalf("recompile: %v", err)
	}

	after, err := os.ReadFile(mk)
	if err != nil {
		t.Fatalf("read after recompile: %v", err)
	}

	// Custom target must be preserved.
	if !strings.Contains(string(after), "custom-target") {
		t.Error("repository-owned custom target was not preserved after recompilation")
	}

	// Must still contain the seeded notice.
	if !strings.Contains(string(after), "repository-owned after creation") {
		t.Error("seeded header was lost after recompilation")
	}

	// Full content must be unchanged.
	if string(after) != customContent {
		t.Errorf("Makefile content changed after recompilation:\nexpected:\n%s\ngot:\n%s", customContent, after)
	}
}

// TestSeededNoticeDistinctFromManagedNotice verifies that seeded and managed
// notices cannot be interchanged without failing tests.
func TestSeededNoticeDistinctFromManagedNotice(t *testing.T) {
	pack, err := LoadCorePack()
	if err != nil {
		t.Fatalf("LoadCorePack: %v", err)
	}

	// Get the generated and seeded notices.
	generated := generatedNotice(pack)
	seeded := seededNotice(pack)

	// They must be different.
	if generated == seeded {
		t.Error("generated and seeded notices must be distinct")
	}

	// Generated must contain "Generated by Leamas".
	if !strings.Contains(generated, "Generated by Leamas") {
		t.Error("generated notice must contain 'Generated by Leamas'")
	}

	// Generated must contain "Do not edit".
	if !strings.Contains(generated, "Do not edit") {
		t.Error("generated notice must contain 'Do not edit'")
	}

	// Seeded must contain "Seeded by Leamas".
	if !strings.Contains(seeded, "Seeded by Leamas") {
		t.Error("seeded notice must contain 'Seeded by Leamas'")
	}

	// Seeded must contain "repository-owned".
	if !strings.Contains(seeded, "repository-owned after creation") {
		t.Error("seeded notice must contain 'repository-owned after creation'")
	}

	// Seeded must NOT contain "Do not edit".
	if strings.Contains(seeded, "Do not edit") {
		t.Error("seeded notice must NOT contain 'Do not edit'")
	}

	// Generated must NOT contain "Seeded by".
	if strings.Contains(generated, "Seeded by") {
		t.Error("generated notice must NOT contain 'Seeded by'")
	}

	// Generated must NOT contain "repository-owned".
	if strings.Contains(generated, "repository-owned") {
		t.Error("generated notice must NOT contain 'repository-owned'")
	}
}

// TestSeededNoticeContainsRequiredFacts verifies the seeded notice contains
// all three required facts per the ACT specification.
func TestSeededNoticeContainsRequiredFacts(t *testing.T) {
	pack, err := LoadCorePack()
	if err != nil {
		t.Fatalf("LoadCorePack: %v", err)
	}

	seeded := seededNotice(pack)

	// Fact 1: Leamas seeded the file.
	if !strings.Contains(seeded, "Seeded by Leamas") {
		t.Error("seeded notice must state that Leamas seeded the file")
	}

	// Fact 2: The repository owns it after creation.
	if !strings.Contains(seeded, "repository-owned after creation") {
		t.Error("seeded notice must state that repository owns the file after creation")
	}

	// Fact 3: Required Factory integration contracts must be preserved.
	if !strings.Contains(seeded, "Factory integration contracts") {
		t.Error("seeded notice must state that Factory integration contracts must be preserved")
	}
}
