// Package digest provides targeted digest generation for Git repositories.
package digest

import (
	"path/filepath"
	"testing"
)

func TestClassifyFile_TestPatterns(t *testing.T) {
	tests := []struct {
		path     string
		expected string
	}{
		{"main_test.go", "test"},
		{"my_test.go", "test"},
		{"helper_test.ts", "test"},
		{"util_test.tsx", "test"},
		{"example.test.ts", "test"},
		{"example.test.tsx", "test"},
		{"test_parser.py", "test"},
		{filepath.Join("tests", "helper.go"), "test"},
		{filepath.Join("tests", "integration", "main.go"), "test"},
	}

	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			result := classifyFile(tt.path)
			if result != tt.expected {
				t.Errorf("classifyFile(%q) = %q, want %q", tt.path, result, tt.expected)
			}
		})
	}
}

func TestClassifyFile_DocPatterns(t *testing.T) {
	tests := []struct {
		path     string
		expected string
	}{
		{"README.md", "doc"},
		{"CHANGELOG.md", "doc"},
		{"guide.adoc", "doc"},
		{"changes.rst", "doc"},
		{filepath.Join("docs", "guide.md"), "doc"},
		{filepath.Join("docs", "api", "reference.md"), "doc"},
	}

	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			result := classifyFile(tt.path)
			if result != tt.expected {
				t.Errorf("classifyFile(%q) = %q, want %q", tt.path, result, tt.expected)
			}
		})
	}
}

func TestClassifyFile_ConfigPatterns(t *testing.T) {
	tests := []struct {
		path     string
		expected string
	}{
		{"Makefile", "config"},
		{"config.mk", "config"},
		{"settings.yaml", "config"},
		{"app.yml", "config"},
		{"config.toml", "config"},
		{"package.json", "config"},
		{filepath.Join(".github", "workflows", "ci.yml"), "config"},
		{".gitlab-ci.yml", "config"},
	}

	for _, tt := range tests {
		t.Run(tt.path, func(t *testing.T) {
			result := classifyFile(tt.path)
			if result != tt.expected {
				t.Errorf("classifyFile(%q) = %q, want %q", tt.path, result, tt.expected)
			}
		})
	}
}

func TestClassifyFile_DefaultToSource(t *testing.T) {
	tests := []string{
		"main.go",
		"util.go",
		"lib/core.go",
		"handler.ts",
		"renderer.tsx",
		"parser.go",
		"middleware.go",
	}

	for _, path := range tests {
		t.Run(path, func(t *testing.T) {
			result := classifyFile(path)
			if result != "source" {
				t.Errorf("classifyFile(%q) = %q, want %q", path, result, "source")
			}
		})
	}
}

func TestIsGeneratedFileContent(t *testing.T) {
	tests := []struct {
		name     string
		content  string
		expected bool
	}{
		{
			"canonical marker",
			"// Code generated by tool DO NOT EDIT.\npackage main\n",
			true,
		},
		{
			"canonical with different tool",
			"// Code generated by protoc-gen-go DO NOT EDIT.\npackage main\n",
			true,
		},
		{
			"go generate is NOT generated",
			"//go:generate something\npackage main\n",
			false,
		},
		{
			"unrelated code generated text",
			"package main\n// This code generates output\nfunc main() {}\n",
			false,
		},
		{
			"not a comment",
			"package main\n// Code generated by tool DO NOT EDIT.\nfunc main() {}\n",
			false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := isGeneratedFileContent(tt.content)
			if result != tt.expected {
				t.Errorf("isGeneratedFileContent() = %v, expected %v", result, tt.expected)
			}
		})
	}
}
