// Package digest provides targeted digest generation for Git repositories.
package digest

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestComputeStats_BasicCounts(t *testing.T) {
	manifest := []ReviewChangedFile{
		{Status: StatusAdded, Path: "new.go"},
		{Status: StatusAdded, Path: "new2.go"},
		{Status: StatusModified, Path: "modified.go"},
		{Status: StatusDeleted, Path: "deleted.go"},
		{Status: StatusUntracked, Path: "untracked.txt"},
		{Status: StatusRenamed, Path: "renamed.go"},
		{Status: StatusCopied, Path: "copied.go"},
	}

	stats := ComputeStats(manifest, "")

	if stats.FilesChanged != 7 {
		t.Errorf("FilesChanged = %d, want 7", stats.FilesChanged)
	}
	if stats.AddedFiles != 2 {
		t.Errorf("AddedFiles = %d, want 2", stats.AddedFiles)
	}
	if stats.ModifiedFiles != 1 {
		t.Errorf("ModifiedFiles = %d, want 1", stats.ModifiedFiles)
	}
	if stats.DeletedFiles != 1 {
		t.Errorf("DeletedFiles = %d, want 1", stats.DeletedFiles)
	}
	if stats.UntrackedFiles != 1 {
		t.Errorf("UntrackedFiles = %d, want 1", stats.UntrackedFiles)
	}
	if stats.RenamedFiles != 1 {
		t.Errorf("RenamedFiles = %d, want 1", stats.RenamedFiles)
	}
	if stats.CopiedFiles != 1 {
		t.Errorf("CopiedFiles = %d, want 1", stats.CopiedFiles)
	}
}

func TestComputeStats_FileClassification(t *testing.T) {
	tmpDir := t.TempDir()

	testFiles := []string{
		"my_test.go",
		"your_test.ts",
		"spec.test.tsx",
		"main.test.ts",
	}
	for _, f := range testFiles {
		path := filepath.Join(tmpDir, f)
		os.WriteFile(path, []byte("package test"), 0644)
	}

	docFiles := []string{
		"README.md",
		"CHANGES.rst",
		filepath.Join("docs", "guide.adoc"),
	}
	for _, f := range docFiles {
		path := filepath.Join(tmpDir, f)
		os.MkdirAll(filepath.Dir(path), 0755)
		os.WriteFile(path, []byte("# Doc"), 0644)
	}

	configFiles := []string{
		"Makefile",
		"config.yaml",
		"settings.toml",
		filepath.Join(".github", "workflows", "ci.yml"),
	}
	for _, f := range configFiles {
		path := filepath.Join(tmpDir, f)
		os.MkdirAll(filepath.Dir(path), 0755)
		os.WriteFile(path, []byte("key: value"), 0644)
	}

	sourceFiles := []string{
		"main.go",
		"util.go",
		"internal/pkg/core.go",
	}
	for _, f := range sourceFiles {
		path := filepath.Join(tmpDir, f)
		os.MkdirAll(filepath.Dir(path), 0755)
		os.WriteFile(path, []byte("package main"), 0644)
	}

	allFiles := append(append(append(testFiles, docFiles...), configFiles...), sourceFiles...)
	manifest := make([]ReviewChangedFile, len(allFiles))
	for i, f := range allFiles {
		manifest[i] = ReviewChangedFile{Status: StatusModified, Path: f}
	}

	stats := ComputeStats(manifest, tmpDir)

	if stats.TestFiles != 4 {
		t.Errorf("TestFiles = %d, want 4", stats.TestFiles)
	}
	if stats.DocFiles != 3 {
		t.Errorf("DocFiles = %d, want 3", stats.DocFiles)
	}
	if stats.ConfigFiles != 4 {
		t.Errorf("ConfigFiles = %d, want 4", stats.ConfigFiles)
	}
	if stats.SourceFiles != 3 {
		t.Errorf("SourceFiles = %d, want 3", stats.SourceFiles)
	}
}

func TestComputeStats_GeneratedFiles(t *testing.T) {
	tmpDir := t.TempDir()

	generatedFile := filepath.Join(tmpDir, "generated.pb.go")
	os.WriteFile(generatedFile, []byte("// Code generated by protoc DO NOT EDIT.\npackage main"), 0644)

	sourceFile := filepath.Join(tmpDir, "main.go")
	os.WriteFile(sourceFile, []byte("package main"), 0644)

	manifest := []ReviewChangedFile{
		{Status: StatusModified, Path: "generated.pb.go"},
		{Status: StatusModified, Path: "main.go"},
	}

	stats := ComputeStats(manifest, tmpDir)

	if stats.GeneratedFiles != 1 {
		t.Errorf("GeneratedFiles = %d, want 1", stats.GeneratedFiles)
	}
	if stats.SourceFiles != 1 {
		t.Errorf("SourceFiles = %d, want 1", stats.SourceFiles)
	}
}

func TestRenderStats_StableKeyOrder(t *testing.T) {
	stats := FileStats{
		FilesChanged:   5,
		AddedFiles:     1,
		ModifiedFiles:  2,
		DeletedFiles:   0,
		RenamedFiles:   0,
		CopiedFiles:    0,
		UntrackedFiles: 2,
		UnmergedFiles:  0,
		BinaryFiles:    0,
		GeneratedFiles: 0,
		TestFiles:      1,
		DocFiles:       1,
		SourceFiles:    2,
		ConfigFiles:    1,
	}

	result := RenderStats(stats)

	expectedOrder := []string{
		"files_changed",
		"added_files",
		"modified_files",
		"deleted_files",
		"renamed_files",
		"copied_files",
		"untracked_files",
		"unmerged_files",
		"binary_files",
		"generated_files",
		"test_files",
		"doc_files",
		"source_files",
		"config_files",
	}

	for i, key := range expectedOrder {
		if i > 0 {
			idx := strings.Index(result, key)
			prevIdx := strings.Index(result, expectedOrder[i-1])
			if idx <= prevIdx {
				t.Errorf("key %q should come after %q", key, expectedOrder[i-1])
			}
		}
	}
}
