// Package digest provides targeted digest generation for Git repositories.
package digest

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestComputeRiskSignals_ProductionWithoutTests(t *testing.T) {
	tmpDir := t.TempDir()

	sourceFile := filepath.Join(tmpDir, "main.go")
	os.WriteFile(sourceFile, []byte("package main"), 0644)

	manifest := []ReviewChangedFile{
		{Status: StatusModified, Path: "main.go"},
	}

	stats := ComputeStats(manifest, tmpDir)
	rs := ComputeRiskSignals(stats, manifest, tmpDir)

	if !rs.ProductionWithoutTests {
		t.Error("production_without_tests should be true when source changes without tests")
	}
	if rs.TestsWithoutProduction {
		t.Error("tests_without_production should be false")
	}
}

func TestComputeRiskSignals_TestsWithoutProduction(t *testing.T) {
	tmpDir := t.TempDir()

	testFile := filepath.Join(tmpDir, "main_test.go")
	os.WriteFile(testFile, []byte("package main"), 0644)

	manifest := []ReviewChangedFile{
		{Status: StatusModified, Path: "main_test.go"},
	}

	stats := ComputeStats(manifest, tmpDir)
	rs := ComputeRiskSignals(stats, manifest, tmpDir)

	if !rs.TestsWithoutProduction {
		t.Error("tests_without_production should be true when only tests change")
	}
	if rs.ProductionWithoutTests {
		t.Error("production_without_tests should be false")
	}
}

func TestComputeRiskSignals_DocsWithoutCode(t *testing.T) {
	tmpDir := t.TempDir()

	docFile := filepath.Join(tmpDir, "README.md")
	os.WriteFile(docFile, []byte("# README"), 0644)

	manifest := []ReviewChangedFile{
		{Status: StatusModified, Path: "README.md"},
	}

	stats := ComputeStats(manifest, tmpDir)
	rs := ComputeRiskSignals(stats, manifest, tmpDir)

	if !rs.DocsWithoutCode {
		t.Error("docs_without_code should be true when only docs change")
	}
}

func TestComputeRiskSignals_DeletedFiles(t *testing.T) {
	manifest := []ReviewChangedFile{
		{Status: StatusDeleted, Path: "deleted.go"},
	}

	stats := ComputeStats(manifest, "")
	rs := ComputeRiskSignals(stats, manifest, "")

	if !rs.DeletedFilesChanged {
		t.Error("deleted_files_changed should be true when a file is deleted")
	}
}

func TestComputeRiskSignals_GeneratedFilesChanged(t *testing.T) {
	tmpDir := t.TempDir()

	generatedFile := filepath.Join(tmpDir, "generated.pb.go")
	os.WriteFile(generatedFile, []byte("// Code generated by tool DO NOT EDIT.\npackage main"), 0644)

	manifest := []ReviewChangedFile{
		{Status: StatusModified, Path: "generated.pb.go"},
	}

	stats := ComputeStats(manifest, tmpDir)
	rs := ComputeRiskSignals(stats, manifest, tmpDir)

	if !rs.GeneratedFilesChanged {
		t.Error("generated_files_changed should be true when a generated file changes")
	}
}

func TestComputeRiskSignals_ConfigFilesChanged(t *testing.T) {
	tmpDir := t.TempDir()

	configFile := filepath.Join(tmpDir, "config.yaml")
	os.WriteFile(configFile, []byte("key: value"), 0644)

	manifest := []ReviewChangedFile{
		{Status: StatusModified, Path: "config.yaml"},
	}

	stats := ComputeStats(manifest, tmpDir)
	rs := ComputeRiskSignals(stats, manifest, tmpDir)

	if !rs.ConfigFilesChanged {
		t.Error("config_files_changed should be true when a config file changes")
	}
}

func TestComputeRiskSignals_LargeFileChanged(t *testing.T) {
	tmpDir := t.TempDir()

	largeFile := filepath.Join(tmpDir, "large.bin")
	largeContent := make([]byte, LargeFileThreshold+1)
	for i := range largeContent {
		largeContent[i] = 'x'
	}
	os.WriteFile(largeFile, largeContent, 0644)

	manifest := []ReviewChangedFile{
		{Status: StatusModified, Path: "large.bin"},
	}

	stats := ComputeStats(manifest, tmpDir)
	rs := ComputeRiskSignals(stats, manifest, tmpDir)

	if !rs.LargeFileChanged {
		t.Error("large_file_changed should be true when a file exceeds threshold")
	}
	if rs.LargeFileThresholdBytes != LargeFileThreshold {
		t.Errorf("large_file_threshold_bytes = %d, want %d", rs.LargeFileThresholdBytes, LargeFileThreshold)
	}
}

func TestRenderRiskSignals_StableKeyOrder(t *testing.T) {
	rs := RiskSignals{
		ProductionWithoutTests:  true,
		TestsWithoutProduction:  false,
		DocsWithoutCode:         false,
		GeneratedFilesChanged:   false,
		ConfigFilesChanged:      true,
		DeletedFilesChanged:     false,
		UnmergedFilesPresent:    false,
		LargeFileChanged:        false,
		LargeFileThresholdBytes: LargeFileThreshold,
	}

	result := RenderRiskSignals(rs)

	expectedOrder := []string{
		"production_without_tests",
		"tests_without_production",
		"docs_without_code",
		"generated_files_changed",
		"config_files_changed",
		"deleted_files_changed",
		"unmerged_files_present",
		"large_file_changed",
		"large_file_threshold_bytes",
	}

	for i, key := range expectedOrder {
		if i > 0 {
			idx := strings.Index(result, key)
			prevIdx := strings.Index(result, expectedOrder[i-1])
			if idx <= prevIdx {
				t.Errorf("key %q should come after %q", key, expectedOrder[i-1])
			}
		}
	}
}

func TestRenderRiskSignals_BooleanValuesLowercase(t *testing.T) {
	rs := RiskSignals{
		ProductionWithoutTests:  true,
		TestsWithoutProduction:  false,
		DocsWithoutCode:         true,
		GeneratedFilesChanged:   false,
		ConfigFilesChanged:      true,
		DeletedFilesChanged:     false,
		UnmergedFilesPresent:    false,
		LargeFileChanged:        true,
		LargeFileThresholdBytes: LargeFileThreshold,
	}

	result := RenderRiskSignals(rs)

	if !strings.Contains(result, "production_without_tests=true") {
		t.Error("expected lowercase true value")
	}
	if !strings.Contains(result, "tests_without_production=false") {
		t.Error("expected lowercase false value")
	}
}
