package closure

import (
	"testing"
)

// plan_run_execution_fields_schema_helpers_test.go centralises
// the small schema-navigation helpers the differential and
// mutation test files share. Splitting it from both files keeps
// every file under the LLM-friendly 400-line threshold.

// workingDirectorySchemaMap walks the standard nested-object
// layout to find /checks/items/properties/working_directory.
// It panics on missing keys because the schema is generated by
// the descriptor and the descriptor always emits those keys.
func workingDirectorySchemaMap(t *testing.T, schema map[string]any) map[string]any {
	t.Helper()
	props, _ := schema["properties"].(map[string]any)
	checks, _ := props["checks"].(map[string]any)
	items, _ := checks["items"].(map[string]any)
	itemsProps, _ := items["properties"].(map[string]any)
	wd, _ := itemsProps["working_directory"].(map[string]any)
	return wd
}

// timeoutSecondsSchemaMap walks the standard nested-object
// layout to find /checks/items/properties/timeout_seconds.
func timeoutSecondsSchemaMap(t *testing.T, schema map[string]any) map[string]any {
	t.Helper()
	props, _ := schema["properties"].(map[string]any)
	checks, _ := props["checks"].(map[string]any)
	items, _ := checks["items"].(map[string]any)
	itemsProps, _ := items["properties"].(map[string]any)
	ts, _ := itemsProps["timeout_seconds"].(map[string]any)
	return ts
}

// pathPolicyMap walks to working_directory and returns the
// x-leamas-repository-relative-path map, creating it if
// absent. The helper exists so the mutation tests can
// overwrite individual extension members.
func pathPolicyMap(t *testing.T, schema map[string]any) map[string]any {
	t.Helper()
	wd := workingDirectorySchemaMap(t, schema)
	pp, ok := wd["x-leamas-repository-relative-path"].(map[string]any)
	if !ok || pp == nil {
		pp = map[string]any{}
		wd["x-leamas-repository-relative-path"] = pp
	}
	return pp
}
