// SPDX-License-Identifier: Apache-2.0

package closure

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strconv"
	"strings"
	"testing"
	"time"
)

func TestV2CanonicalArtifactsStableAndSanitized(t *testing.T) {
	input := canonicalArtifactTestInput()
	first, err := generateV2CanonicalArtifacts(input)
	if err != nil {
		t.Fatal(err)
	}
	second, err := generateV2CanonicalArtifacts(input)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Fatal("canonical artifacts changed across identical runs")
	}
	if len(first.ManifestBytes) == 0 || first.ManifestBytes[len(first.ManifestBytes)-1] != '\n' ||
		len(first.ReportBytes) == 0 || first.ReportBytes[len(first.ReportBytes)-1] != '\n' {
		t.Fatal("canonical artifacts must end in one deterministic newline")
	}
	if first.ManifestSHA256 != SHA256Hex(first.ManifestBytes) || first.ReportSHA256 != SHA256Hex(first.ReportBytes) {
		t.Fatal("artifact SHA-256 does not bind generated bytes")
	}
	forbiddenFields := []string{
		"started_at_utc", "finished_at_utc", "duration_ms", "detached_evidence",
		"evidence_path", "TO_BE_FILLED", "leamas_version", "binary_sha256", "branch",
		"stdout_sha256", "stderr_sha256", "stdout_byte_count", "stderr_byte_count",
		"output_bytes_observed",
	}
	for _, forbidden := range forbiddenFields {
		if bytes.Contains(first.ManifestBytes, []byte(forbidden)) || bytes.Contains(first.ReportBytes, []byte(forbidden)) {
			t.Fatalf("canonical artifacts contain unstable or forbidden field %q", forbidden)
		}
	}
	var manifest map[string]any
	if err := json.Unmarshal(first.ManifestBytes, &manifest); err != nil {
		t.Fatal(err)
	}
	if manifest["contract_version"] != float64(1) || manifest["closure_protocol_version"] != float64(2) {
		t.Fatalf("version fields = %#v", manifest)
	}
}

func TestV2CanonicalArtifactsIgnoreAmbientClock(t *testing.T) {
	input := canonicalArtifactTestInput()
	first, err := generateV2CanonicalArtifacts(input)
	if err != nil {
		t.Fatal(err)
	}
	time.Sleep(time.Millisecond)
	second, err := generateV2CanonicalArtifacts(input)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first.ManifestBytes, second.ManifestBytes) || !bytes.Equal(first.ReportBytes, second.ReportBytes) {
		t.Fatal("ambient clock affected canonical artifact bytes")
	}
}

func TestBuildV2ClosureObjectsGeometryAndDeterminism(t *testing.T) {
	for _, objectFormat := range supportedObjectFormats(t) {
		t.Run(string(objectFormat), func(t *testing.T) {
			repo, subject, subjectTree := prepareObjectTransactionRepository(t, objectFormat)
			artifacts := mustCanonicalArtifacts(t)
			indexBefore := readRealIndex(t, repo)

			result, err := buildV2ClosureObjects(context.Background(), RealGit{}, repo, objectFormat, subject, subjectTree, objectTransactionActID, artifacts)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(indexBefore, readRealIndex(t, repo)) {
				t.Fatal("alternate-index construction changed the real index")
			}
			assertObjectTransactionResult(t, repo, objectFormat, subject, subjectTree, artifacts, result)

			v2Git(t, repo, "config", "user.name", "Ambient Other")
			v2Git(t, repo, "config", "user.email", "ambient-other@example.invalid")
			again, err := buildV2ClosureObjects(context.Background(), RealGit{}, repo, objectFormat, subject, subjectTree, objectTransactionActID, artifacts)
			if err != nil {
				t.Fatal(err)
			}
			if result != again {
				t.Fatalf("ambient Git identity changed object result: first=%+v second=%+v", result, again)
			}
		})
	}
}

func TestBuildV2ClosureObjectsRejectsPreExistingCanonicalPath(t *testing.T) {
	repo, subject, subjectTree := prepareObjectTransactionRepository(t, ObjectFormatSHA1)
	path := filepath.Join(repo, canonicalV2ManifestPath(objectTransactionActID))
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("existing\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	v2Git(t, repo, "add", canonicalV2ManifestPath(objectTransactionActID))
	v2Git(t, repo, "commit", "-m", "pre-existing canonical path")
	subject = v2Git(t, repo, "rev-parse", "HEAD")
	subjectTree = v2Git(t, repo, "rev-parse", "HEAD^{tree}")
	_, err := buildV2ClosureObjects(context.Background(), RealGit{}, repo, ObjectFormatSHA1, subject, subjectTree, objectTransactionActID, mustCanonicalArtifacts(t))
	if err == nil || !strings.Contains(err.Error(), "already exists") {
		t.Fatalf("expected pre-existing path rejection, got %v", err)
	}
}

func TestBuildV2ClosureObjectsFailureWindowsAreIsolated(t *testing.T) {
	windows := []struct {
		name       string
		command    string
		occurrence int
	}{
		{name: "read-tree", command: "read-tree", occurrence: 1},
		{name: "first update-index", command: "update-index", occurrence: 1},
		{name: "second update-index", command: "update-index", occurrence: 2},
		{name: "write-tree", command: "write-tree", occurrence: 1},
	}
	for _, window := range windows {
		t.Run(window.name, func(t *testing.T) {
			repo, subject, subjectTree := prepareObjectTransactionRepository(t, ObjectFormatSHA1)
			before := captureRepositoryWindow(t, repo)
			git := &recordingIndexGit{
				delegate: RealGit{}, failCommand: window.command,
				failOccurrence: window.occurrence,
			}
			_, err := buildV2ClosureObjects(context.Background(), git, repo, ObjectFormatSHA1,
				subject, subjectTree, objectTransactionActID, mustCanonicalArtifacts(t))
			if err == nil {
				t.Fatalf("expected injected %s failure", window.name)
			}
			if git.indexPath == "" {
				t.Fatal("no alternate index was observed")
			}
			if _, statErr := os.Lstat(git.indexPath); !errors.Is(statErr, os.ErrNotExist) {
				t.Fatalf("temporary index remains after failure: %v", statErr)
			}
			assertRepositoryWindowEqual(t, before, captureRepositoryWindow(t, repo))
		})
	}
}

const objectTransactionActID = "ACT-LEAMAS-V2-OBJECT-TRANSACTION01"

func canonicalArtifactTestInput() v2CanonicalArtifactInput {
	exitCode := 0
	return v2CanonicalArtifactInput{
		ActID:         objectTransactionActID,
		PlanPath:      "docs/closure-plans/" + objectTransactionActID + ".json",
		PlanSHA256:    strings.Repeat("a", 64),
		PlanBlobOID:   strings.Repeat("b", 40),
		FreezeCommit:  strings.Repeat("c", 40),
		FreezeTree:    strings.Repeat("d", 40),
		SubjectCommit: strings.Repeat("e", 40),
		SubjectTree:   strings.Repeat("f", 40),
		Branch:        "main",
		Runner: RunnerIdentity{
			LeamasVersion: "test", BinarySHA256: strings.Repeat("1", 64),
			VCSRevision: strings.Repeat("e", 40),
		},
		Checks: []CheckResult{{
			CheckID: "authority-check", SubjectTreeOID: strings.Repeat("f", 40),
			Argv: []string{"go", "version"}, WorkingDirectory: ".",
			OverriddenEnvironment: []string{}, StartedAtUTC: "2026-01-01T00:00:00Z",
			FinishedAtUTC: "2026-01-01T00:00:01Z", DurationMS: 1000,
			ExitCode: &exitCode, Status: CheckStatusPass,
			StdoutSHA256: strings.Repeat("2", 64), StderrSHA256: strings.Repeat("3", 64),
			CleanupStatus: CleanupPass,
		}},
		PatchHygiene:  PatchHygiene{Status: CheckStatusPass},
		ClosurePolicy: ClosurePolicyResult{TrackedFullDigestStatus: CheckStatusPass},
	}
}

func mustCanonicalArtifacts(t *testing.T) v2CanonicalArtifacts {
	t.Helper()
	artifacts, err := generateV2CanonicalArtifacts(canonicalArtifactTestInput())
	if err != nil {
		t.Fatal(err)
	}
	return artifacts
}

func supportedObjectFormats(t *testing.T) []ObjectFormat {
	t.Helper()
	formats := []ObjectFormat{ObjectFormatSHA1}
	probe := t.TempDir()
	result := RealGit{}.Run(context.Background(), probe, "init", "--object-format=sha256")
	if result.Err == nil && result.ExitCode == 0 {
		formats = append(formats, ObjectFormatSHA256)
	}
	return formats
}

func prepareObjectTransactionRepository(t *testing.T, objectFormat ObjectFormat) (string, string, string) {
	t.Helper()
	repo := t.TempDir()
	args := []string{"init", "-b", "main"}
	if objectFormat == ObjectFormatSHA256 {
		args = append(args, "--object-format=sha256")
	}
	v2Git(t, repo, args...)
	v2Git(t, repo, "config", "user.name", "Ambient User")
	v2Git(t, repo, "config", "user.email", "ambient@example.invalid")
	if err := os.WriteFile(filepath.Join(repo, "README.md"), []byte("subject\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	v2Git(t, repo, "add", "README.md")
	v2Git(t, repo, "commit", "-m", "subject")
	return repo, v2Git(t, repo, "rev-parse", "HEAD"), v2Git(t, repo, "rev-parse", "HEAD^{tree}")
}

type repositoryWindow struct {
	index  []byte
	status []byte
	head   []byte
	refs   []byte
}

func captureRepositoryWindow(t *testing.T, repo string) repositoryWindow {
	t.Helper()
	return repositoryWindow{
		index:  readRealIndex(t, repo),
		status: rawGitStdout(t, repo, "status", "--porcelain=v1", "--untracked-files=normal"),
		head:   rawGitStdout(t, repo, "rev-parse", "HEAD"),
		refs:   rawGitStdout(t, repo, "for-each-ref", "--format=%(refname)%00%(objectname)"),
	}
}

func assertRepositoryWindowEqual(t *testing.T, want, got repositoryWindow) {
	t.Helper()
	if !reflect.DeepEqual(want, got) {
		t.Fatalf("repository state changed across failed object transaction:\nwant=%q\ngot=%q", want, got)
	}
}

func readRealIndex(t *testing.T, repo string) []byte {
	t.Helper()
	gitDir := v2Git(t, repo, "rev-parse", "--git-dir")
	if !filepath.IsAbs(gitDir) {
		gitDir = filepath.Join(repo, gitDir)
	}
	data, err := os.ReadFile(filepath.Join(gitDir, "index"))
	if err != nil {
		t.Fatal(err)
	}
	return data
}

func assertObjectTransactionResult(t *testing.T, repo string, format ObjectFormat, subject, subjectTree string, artifacts v2CanonicalArtifacts, result v2ClosureObjects) {
	t.Helper()
	if err := ValidateOIDWithFormat("closure tree", result.TreeOID, format); err != nil {
		t.Fatal(err)
	}
	if err := ValidateOIDWithFormat("closure commit", result.CommitOID, format); err != nil {
		t.Fatal(err)
	}
	manifestPath := canonicalV2ManifestPath(objectTransactionActID)
	reportPath := canonicalV2ReportPath(objectTransactionActID)
	diff := v2Git(t, repo, "diff-tree", "--no-commit-id", "--name-status", "-r", subjectTree, result.TreeOID)
	wantDiff := "A\t" + reportPath + "\nA\t" + manifestPath
	if diff != wantDiff {
		t.Fatalf("tree diff = %q, want %q", diff, wantDiff)
	}
	if got := v2Git(t, repo, "rev-parse", result.TreeOID+":"+manifestPath); got != result.ManifestBlobOID {
		t.Fatalf("manifest tree blob = %s, want %s", got, result.ManifestBlobOID)
	}
	if got := v2Git(t, repo, "rev-parse", result.TreeOID+":"+reportPath); got != result.ReportBlobOID {
		t.Fatalf("report tree blob = %s, want %s", got, result.ReportBlobOID)
	}
	if got := rawGitStdout(t, repo, "cat-file", "blob", result.ManifestBlobOID); !bytes.Equal(got, artifacts.ManifestBytes) {
		t.Fatal("manifest blob bytes do not exactly match generated bytes")
	}
	if got := rawGitStdout(t, repo, "cat-file", "blob", result.ReportBlobOID); !bytes.Equal(got, artifacts.ReportBytes) {
		t.Fatal("report blob bytes do not exactly match generated bytes")
	}
	parents := strings.Fields(v2Git(t, repo, "rev-list", "--parents", "-n", "1", result.CommitOID))
	if len(parents) != 2 || parents[1] != subject {
		t.Fatalf("closure parents = %v, want exactly %s", parents, subject)
	}
	subjectEpoch := v2Git(t, repo, "show", "-s", "--format=%ct", subject)
	closureEpoch := v2Git(t, repo, "show", "-s", "--format=%ct", result.CommitOID)
	if closureEpoch != incrementDecimalEpoch(t, subjectEpoch) {
		t.Fatalf("closure epoch = %s, want subject+1", closureEpoch)
	}
}

func rawGitStdout(t *testing.T, repo string, args ...string) []byte {
	t.Helper()
	result := RealGit{}.Run(context.Background(), repo, args...)
	if result.Err != nil || result.ExitCode != 0 {
		t.Fatalf("git %v: %v (exit %d): %s", args, result.Err, result.ExitCode, result.Stderr)
	}
	return append([]byte(nil), result.Stdout...)
}

func incrementDecimalEpoch(t *testing.T, raw string) string {
	t.Helper()
	parsed, err := strconv.ParseInt(raw, 10, 64)
	if err != nil {
		t.Fatal(err)
	}
	return strconv.FormatInt(parsed+1, 10)
}

type recordingIndexGit struct {
	delegate       RealGit
	failCommand    string
	failOccurrence int
	commandCalls   map[string]int
	indexPath      string
}

func (g *recordingIndexGit) Run(ctx context.Context, dir string, args ...string) gitCommandResult {
	return g.delegate.Run(ctx, dir, args...)
}

func (g *recordingIndexGit) RunWithStdin(ctx context.Context, dir, stdin string, args ...string) gitCommandResult {
	return g.delegate.RunWithStdin(ctx, dir, stdin, args...)
}

func (g *recordingIndexGit) RunWithStdinAndEnv(ctx context.Context, dir, stdin string, env []string, args ...string) gitCommandResult {
	return g.delegate.RunWithStdinAndEnv(ctx, dir, stdin, env, args...)
}

func (g *recordingIndexGit) RunWithEnv(ctx context.Context, dir string, env []string, args ...string) gitCommandResult {
	for _, item := range env {
		if strings.HasPrefix(item, "GIT_INDEX_FILE=") {
			g.indexPath = strings.TrimPrefix(item, "GIT_INDEX_FILE=")
		}
	}
	if len(args) > 0 {
		if g.commandCalls == nil {
			g.commandCalls = make(map[string]int)
		}
		g.commandCalls[args[0]]++
		occurrence := g.failOccurrence
		if occurrence == 0 {
			occurrence = 1
		}
		if args[0] == g.failCommand && g.commandCalls[args[0]] == occurrence {
			return gitCommandResult{ExitCode: 1, Err: errors.New("injected failure"), Stderr: []byte("injected failure")}
		}
	}
	return g.delegate.RunWithEnv(ctx, dir, env, args...)
}
