// SPDX-License-Identifier: Apache-2.0

package closure

import (
	"bytes"
	"context"
	"strings"
	"testing"
)

func TestV2TagObjectExactBytesAndTarget(t *testing.T) {
	for _, format := range supportedObjectFormats(t) {
		t.Run(string(format), func(t *testing.T) {
			repo, subject, subjectTree := prepareObjectTransactionRepository(t, format)
			artifacts := mustCanonicalArtifacts(t)
			objects, err := buildV2ClosureObjects(context.Background(), RealGit{}, repo,
				format, subject, subjectTree, objectTransactionActID, artifacts)
			if err != nil {
				t.Fatal(err)
			}
			input := tagTestInput(format, subject, subjectTree, objects, artifacts)
			created, err := createV2TagObject(context.Background(), RealGit{}, repo, format, input)
			if err != nil {
				t.Fatal(err)
			}
			stored := rawGitStdout(t, repo, "cat-file", "tag", created.OID)
			if !bytes.Equal(stored, created.Bytes) {
				t.Fatal("stored tag bytes do not exactly match generated bytes")
			}
			if !bytes.HasPrefix(created.Bytes, []byte("object "+objects.CommitOID+"\ntype commit\ntag "+canonicalV2TagName(input.ActID)+"\n")) {
				t.Fatalf("tag header is not exact:\n%s", created.Bytes)
			}
			if target := v2Git(t, repo, "rev-parse", created.OID+"^{commit}"); target != objects.CommitOID {
				t.Fatalf("tag target = %s, want C %s", target, objects.CommitOID)
			}
			if refs := rawGitStdout(t, repo, "for-each-ref", "refs/tags"); len(refs) != 0 {
				t.Fatalf("mktag changed refs: %q", refs)
			}
		})
	}
}

func TestV2TagObjectReproducibleAndRuntimeSensitive(t *testing.T) {
	repo, subject, subjectTree := prepareObjectTransactionRepository(t, ObjectFormatSHA1)
	artifacts := mustCanonicalArtifacts(t)
	objects, err := buildV2ClosureObjects(context.Background(), RealGit{}, repo,
		ObjectFormatSHA1, subject, subjectTree, objectTransactionActID, artifacts)
	if err != nil {
		t.Fatal(err)
	}
	input := tagTestInput(ObjectFormatSHA1, subject, subjectTree, objects, artifacts)
	first, err := createV2TagObject(context.Background(), RealGit{}, repo, ObjectFormatSHA1, input)
	if err != nil {
		t.Fatal(err)
	}
	second, err := createV2TagObject(context.Background(), RealGit{}, repo, ObjectFormatSHA1, input)
	if err != nil {
		t.Fatal(err)
	}
	if first.OID != second.OID || !bytes.Equal(first.Bytes, second.Bytes) {
		t.Fatal("identical runtime evidence did not reproduce T")
	}
	input.RunnerBinarySHA = strings.Repeat("9", 64)
	changed, err := createV2TagObject(context.Background(), RealGit{}, repo, ObjectFormatSHA1, input)
	if err != nil {
		t.Fatal(err)
	}
	if changed.OID == first.OID {
		t.Fatal("runtime evidence change did not change T")
	}
}

func TestV2TagObjectRejectsInvalidNameAndTarget(t *testing.T) {
	repo, subject, subjectTree := prepareObjectTransactionRepository(t, ObjectFormatSHA1)
	artifacts := mustCanonicalArtifacts(t)
	objects, err := buildV2ClosureObjects(context.Background(), RealGit{}, repo,
		ObjectFormatSHA1, subject, subjectTree, objectTransactionActID, artifacts)
	if err != nil {
		t.Fatal(err)
	}
	input := tagTestInput(ObjectFormatSHA1, subject, subjectTree, objects, artifacts)
	input.TagName = "other/tag"
	if _, err := createV2TagObject(context.Background(), RealGit{}, repo, ObjectFormatSHA1, input); err == nil {
		t.Fatal("non-canonical tag name accepted")
	}
	input = tagTestInput(ObjectFormatSHA1, subject, subjectTree, objects, artifacts)
	input.ClosureCommit = strings.Repeat("f", 40)
	if _, err := createV2TagObject(context.Background(), RealGit{}, repo, ObjectFormatSHA1, input); err == nil {
		t.Fatal("missing tag target object accepted")
	}
}

func tagTestInput(format ObjectFormat, subject, subjectTree string,
	objects v2ClosureObjects, artifacts v2CanonicalArtifacts) v2TagInput {
	width := 40
	if format == ObjectFormatSHA256 {
		width = 64
	}
	return v2TagInput{
		ActID: objectTransactionActID, ClosureCommit: objects.CommitOID, ClosureTree: objects.TreeOID,
		FreezeCommit: subject, FreezeTree: subjectTree, SubjectCommit: subject, SubjectTree: subjectTree,
		PlanBlobOID: strings.Repeat("a", width), PlanSHA256: strings.Repeat("1", 64),
		ManifestBlobOID: objects.ManifestBlobOID, ManifestSHA256: artifacts.ManifestSHA256,
		ReportBlobOID: objects.ReportBlobOID, ReportSHA256: artifacts.ReportSHA256,
		EvidenceSHA256: strings.Repeat("2", 64), RunnerRevision: subject,
		RunnerBinarySHA: strings.Repeat("3", 64),
	}
}
