// SPDX-License-Identifier: Apache-2.0

// Package closure - runtime_context.go implements the typed closure
// runtime context required by Phase 1 of
// ACT-LEAMAS-FACTORY-CLOSURE-RUNTIME-CONTEXT-AND-EXECUTE01.
//
// RuntimeContext is the single typed carrier of freeze and subject
// identities used by every closure-runtime subsystem (gate capture,
// binary authority, evidence publication, commit/tag creation). It
// removes the long-standing reliance on ambient shell variables
// (LEAMAS_FREEZE_OID, LEAMAS_SUBJECT_OID, ...) by encoding every
// identity in a Go struct that cannot be partially supplied.
//
// The file declares the type only. The resolver, authority rules,
// and concrete bindings live in runtime_context_resolver.go.

package closure

import (
	"context"
	"errors"
	"fmt"
	"strings"
)

// RuntimeContext is the typed binding between a frozen closure plan and
// the implementation commit it describes. Every field is populated by
// the resolver from the Git object database; no field may be supplied
// from ambient environment variables or hand-written text.
type RuntimeContext struct {
	// ACTID is the closed-form ACT identifier (e.g.
	// "ACT-LEAMAS-FACTORY-CLOSURE-RUNTIME-CONTEXT-AND-EXECUTE01").
	ACTID string `json:"act_id"`

	// RepositoryRoot is the absolute, symlink-resolved path of the
	// repository the resolver was bound to.
	RepositoryRoot string `json:"repository_root"`
	// RunID is a short opaque identifier recorded with the run
	// bundle. It is generated by the resolver, never taken from
	// ambient state.
	RunID string `json:"run_id"`

	// FreezeCommit is the commit OID obtained from
	// `git rev-parse <freeze>^{commit}`.
	FreezeCommit string `json:"freeze_commit"`
	// FreezeTree is the tree OID obtained from
	// `git rev-parse FreezeCommit^{tree}`.
	FreezeTree string `json:"freeze_tree"`

	// SubjectCommit is the commit OID obtained from
	// `git rev-parse <subject>^{commit}`.
	SubjectCommit string `json:"subject_commit"`
	// SubjectTree is the tree OID obtained from
	// `git rev-parse SubjectCommit^{tree}`.
	SubjectTree string `json:"subject_tree"`

	// PlanPath is the repository-relative path of the frozen plan
	// blob (e.g. "docs/closure-plans/<ACT-ID>.json").
	PlanPath string `json:"plan_path"`
	// PlanBlob is the blob OID obtained from
	// `git rev-parse <freeze>:<plan_path>`.
	PlanBlob string `json:"plan_blob"`
	// PlanSHA256 is the SHA-256 of the literal PlanBytes the
	// resolver loaded from PlanBlob.
	PlanSHA256 string `json:"plan_sha256"`

	// EvidenceDirectory is the absolute, symlink-resolved path of
	// the evidence directory the resolver will publish to. It is
	// guaranteed to resolve OUTSIDE the target repository.
	EvidenceDirectory string `json:"evidence_directory"`
	// StartedAt is the RFC3339Nano UTC timestamp at which the
	// resolver produced this RuntimeContext.
	StartedAt string `json:"started_at"`
}

// RuntimeContextResolver is the interface every production runtime
// uses to obtain a RuntimeContext. Tests inject a fake resolver so
// the gate capture, binary authority, and evidence publication code
// paths can run hermetically.
//
// Implementations MUST:
//
//   - resolve every field via the supplied gitClient;
//   - validate FreezeCommit != SubjectCommit;
//   - validate FreezeCommit is an ancestor of SubjectCommit;
//   - validate the object format is supported (sha1);
//   - validate the plan path is repository-relative and confined;
//   - validate the caller worktree is clean before producing the
//     RuntimeContext.
//
// No field may be read from ambient environment variables.
type RuntimeContextResolver interface {
	Resolve(
		ctx context.Context,
		repositoryRoot string,
		actID string,
		freezeRevision string,
		subjectRevision string,
		planPath string,
		evidenceDirectory string,
	) (RuntimeContext, error)
}

// RuntimeContextError is returned by Resolve when a precondition
// fails. The Kind classifies the failure so callers can dispatch
// diagnostics and exit codes deterministically.
type RuntimeContextError struct {
	Field string
	Kind  string
	Want  string
	Got   string
}

func (e *RuntimeContextError) Error() string {
	switch e.Kind {
	case "empty_field":
		return fmt.Sprintf("runtime context: field %q is empty", e.Field)
	case "freeze_equals_subject":
		return fmt.Sprintf("runtime context: freeze commit equals subject commit (%s)", e.Got)
	case "freeze_not_ancestor":
		return fmt.Sprintf("runtime context: freeze %s is not an ancestor of subject %s", e.Want, e.Got)
	case "unsupported_object_format":
		return fmt.Sprintf("runtime context: object format %q is not supported", e.Got)
	case "plan_path_invalid":
		return fmt.Sprintf("runtime context: plan path %q is invalid (%s)", e.Got, e.Want)
	case "dirty_worktree":
		return fmt.Sprintf("runtime context: caller worktree is not clean")
	case "oid_mismatch":
		return fmt.Sprintf("runtime context: %s expected %s got %s", e.Field, e.Want, e.Got)
	}
	return fmt.Sprintf("runtime context: %s failure (want=%s got=%s)", e.Field, e.Want, e.Got)
}

// IsRuntimeContextError reports whether err is a typed
// RuntimeContextError.
func IsRuntimeContextError(err error) bool {
	var target *RuntimeContextError
	return errors.As(err, &target)
}

// runtimeContextFieldNames is the canonical ordering used by tests
// and JSON serialization. It exists so the matrix test can iterate
// every field deterministically.
var runtimeContextFieldNames = []string{
	"act_id",
	"repository_root",
	"run_id",
	"freeze_commit",
	"freeze_tree",
	"subject_commit",
	"subject_tree",
	"plan_path",
	"plan_blob",
	"plan_sha256",
	"evidence_directory",
	"started_at",
}

// canonicalPlaceholderPrefix is the prefix shared by every runtime
// placeholder. The constant lives here so the placeholder authority
// (runtime_placeholders.go) and the resolver agree on the spelling.
const canonicalPlaceholderPrefix = "runtime."

// placeholderNameForField converts a runtime context field name to
// its canonical placeholder spelling (e.g. "freeze_commit" ->
// "runtime.freeze_commit"). It is the single authority for the
// mapping; both the placeholder expander and the validation matrix
// read from it.
func placeholderNameForField(field string) string {
	field = strings.TrimSpace(field)
	if field == "" {
		return ""
	}
	if !strings.HasPrefix(field, canonicalPlaceholderPrefix) {
		field = canonicalPlaceholderPrefix + field
	}
	return strings.TrimPrefix(field, canonicalPlaceholderPrefix+"")
}

// PlaceholderNames returns the canonical placeholder vocabulary in
// the same order as runtimeContextFieldNames. The list is the
// authoritative set: adding a field requires updating it.
func PlaceholderNames() []string {
	names := make([]string, len(runtimeContextFieldNames))
	for i, field := range runtimeContextFieldNames {
		names[i] = canonicalPlaceholderPrefix + field
	}
	return names
}
