// Package dupcode provides tests for duplicate code detection.
package dupcode

import (
	"os"
	"path/filepath"
	"testing"

	"go/token"
)

func TestDefaultConfig(t *testing.T) {
	cfg := DefaultConfig()
	if cfg.MinLines != 40 {
		t.Errorf("expected MinLines=40, got %d", cfg.MinLines)
	}
	if cfg.MinTokens != 400 {
		t.Errorf("expected MinTokens=400, got %d", cfg.MinTokens)
	}
	if len(cfg.ExcludeDirs) == 0 {
		t.Error("expected ExcludeDirs to be non-empty")
	}
}

func TestIsGeneratedFile(t *testing.T) {
	tmpDir := t.TempDir()

	tests := []struct {
		name     string
		content  string
		expected bool
	}{
		{
			name:     "canonical marker",
			content:  "// Code generated by tool DO NOT EDIT.\npackage main\n",
			expected: true,
		},
		{
			name:     "canonical with different tool",
			content:  "// Code generated by protoc-gen-go DO NOT EDIT.\npackage main\n",
			expected: true,
		},
		{
			name:     "go generate is NOT generated",
			content:  "//go:generate something\npackage main\n",
			expected: false,
		},
		{
			name:     "normal file",
			content:  "package main\nfunc main() {}\n",
			expected: false,
		},
		{
			name:     "unrelated code generated text",
			content:  "package main\n// This code generates output\nfunc main() {}\n",
			expected: false,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(tmpDir, "test.go")
			if err := os.WriteFile(path, []byte(tc.content), 0644); err != nil {
				t.Fatalf("failed to write test file: %v", err)
			}
			result := isGeneratedFile(path)
			if result != tc.expected {
				t.Errorf("isGeneratedFile(%q) = %v, expected %v", tc.name, result, tc.expected)
			}
		})
	}
}

func TestDeduplicateOccurrences(t *testing.T) {
	occs := []Occurrence{
		{Path: "file.go", StartLine: 10, EndLine: 20},
		{Path: "file.go", StartLine: 15, EndLine: 25},
		{Path: "file.go", StartLine: 30, EndLine: 40},
	}

	result := deduplicateOccurrences(occs)

	if len(result) != 2 {
		t.Errorf("expected 2 occurrences, got %d", len(result))
	}
}

func TestNormalizeFingerprint(t *testing.T) {
	tokens := []token.Token{token.IDENT, token.STRING, token.IDENT}
	fp := normalizeFingerprint(tokens)
	if fp == "" {
		t.Error("expected non-empty fingerprint")
	}
}

func TestTruncateFingerprint(t *testing.T) {
	tests := []struct {
		input    string
		expected string
	}{
		{"short", "short"},
		{"exactly40charactersisokayforthisone12345", "exactly40charactersisokayforthisone12345"},
		{"this is a very long fingerprint that should be truncated", "this is a very long fingerprint that sho..."},
	}

	for _, tc := range tests {
		result := truncateFingerprint(tc.input)
		if result != tc.expected {
			t.Errorf("truncateFingerprint(%q) = %q, expected %q", tc.input, result, tc.expected)
		}
	}
}

func TestListGoFiles(t *testing.T) {
	tmpDir := t.TempDir()

	// Files we want to find
	wantFound := map[string]string{
		"main.go":         "package main\nfunc main() {}\n",
		"util.go":         "package main\nfunc util() {}\n",
		"subpkg/extra.go": "package subpkg\nfunc extra() {}\n",
		"normal_code.go":  "// Code generated tool output\npackage main\nfunc normal() {}\n",
	}

	// Files we want to exclude
	wantAbsent := map[string]string{
		"util_test.go":    "package main\nfunc TestUtil(t *testing.T) {}\n",
		"generated.pb.go": "package main\n// Code generated DO NOT EDIT.\nfunc generated() {}\n",
		"vendor/pkg.go":   "package vendor\nfunc vendor() {}\n",
	}

	for name, content := range wantFound {
		path := filepath.Join(tmpDir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			t.Fatalf("failed to create dir for %s: %v", name, err)
		}
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			t.Fatalf("failed to write %s: %v", name, err)
		}
	}

	for name, content := range wantAbsent {
		path := filepath.Join(tmpDir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
			t.Fatalf("failed to create dir for %s: %v", name, err)
		}
		if err := os.WriteFile(path, []byte(content), 0644); err != nil {
			t.Fatalf("failed to write %s: %v", name, err)
		}
	}

	cfg := DefaultConfig()

	found, err := listGoFiles(tmpDir, cfg)
	if err != nil {
		t.Fatalf("listGoFiles failed: %v", err)
	}

	foundMap := make(map[string]bool)
	for _, f := range found {
		rel, _ := filepath.Rel(tmpDir, f)
		foundMap[rel] = true
	}

	for name := range wantFound {
		if !foundMap[name] {
			t.Errorf("expected to find %s", name)
		}
	}

	for name := range wantAbsent {
		if foundMap[name] {
			t.Errorf("expected %s to be excluded", name)
		}
	}
}

func TestCheckRepo_NoDuplicates(t *testing.T) {
	tmpDir := t.TempDir()

	file1 := filepath.Join(tmpDir, "file1.go")
	if err := os.WriteFile(file1, []byte(`package main
func funcA() {
	x := 1
	y := 2
}
`), 0644); err != nil {
		t.Fatalf("failed to write file1: %v", err)
	}

	file2 := filepath.Join(tmpDir, "file2.go")
	if err := os.WriteFile(file2, []byte(`package main
func funcB() {
	a := 3
	b := 4
}
`), 0644); err != nil {
		t.Fatalf("failed to write file2: %v", err)
	}

	cfg := DefaultConfig()
	cfg.MinLines = 5
	cfg.MinTokens = 20

	findings, err := CheckRepo(tmpDir, cfg)
	if err != nil {
		t.Fatalf("CheckRepo failed: %v", err)
	}

	if len(findings) != 0 {
		t.Errorf("expected no findings, got %d", len(findings))
	}
}

func TestCheckRepo_WithDuplicates(t *testing.T) {
	tmpDir := t.TempDir()

	// Large code block with enough tokens (MinLines=15, MinTokens=150)
	identicalCode := `package main

import "fmt"

func processData() {
	data := make([]int, 0)
	for i := 0; i < 30; i++ {
		data = append(data, i*2)
		data = append(data, i*3)
	}
	result := 0
	for _, v := range data {
		result += v
	}
	fmt.Println("Processing data:", result)
}

func processMore() {
	data := make([]int, 0)
	for i := 0; i < 30; i++ {
		data = append(data, i*2)
		data = append(data, i*3)
	}
	result := 0
	for _, v := range data {
		result += v
	}
	fmt.Println("Processing more:", result)
}
`

	file1 := filepath.Join(tmpDir, "file1.go")
	if err := os.WriteFile(file1, []byte(identicalCode), 0644); err != nil {
		t.Fatalf("failed to write file1: %v", err)
	}

	file2 := filepath.Join(tmpDir, "file2.go")
	if err := os.WriteFile(file2, []byte(identicalCode), 0644); err != nil {
		t.Fatalf("failed to write file2: %v", err)
	}

	cfg := DefaultConfig()
	cfg.MinLines = 15
	cfg.MinTokens = 150

	findings, err := CheckRepo(tmpDir, cfg)
	if err != nil {
		t.Fatalf("CheckRepo failed: %v", err)
	}

	if len(findings) == 0 {
		t.Fatal("expected to detect duplicates but found none")
	}
}
