// Package dupcode provides duplicate code detection for Go source files.
package dupcode

import (
	"bytes"
	"fmt"
	"go/scanner"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// AlgorithmVersion is the version of the duplicate detection algorithm.
// Version 1: Sliding window detection with basic deduplication.
// Version 2: Sliding window detection with coalescing of overlapping windows
// Version 3: Deterministic maximal clone detection via aligned seed-match chaining.
// Version 4: Truthful maximal clone detection with content-based seed matching,
//
//	offset-independent chaining, and complete token fingerprinting.
//
// Algorithm v4 corrects v3 semantics:
// - Matches seeds by content, not absolute token position.
// - Chains across different seed fingerprints within the same clone body.
// - Generates occurrences from maximal token ranges, not individual seed windows.
// - Fingerprints the complete normalized token sequence for stable identity.
const AlgorithmVersion = 4

// generatedMarker matches the canonical Go generated-file marker format.
// Per cmd/go, matches lines like: "// Code generated by ... DO NOT EDIT."
var generatedMarker = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

// Config holds configuration for duplicate code detection.
type Config struct {
	Root                string
	MinLines            int
	MinTokens           int
	ExcludeDirs         []string
	ExcludeFileSuffixes []string
	IgnoreGenerated     bool
}

// DefaultConfig returns the default configuration.
// These thresholds are aligned with the gate policy of MinLines=40, MinTokens=400.
// The baseline + ratchet model allows these lower thresholds while tolerating
// existing historical duplication through the committed baseline.
func DefaultConfig() Config {
	return Config{
		MinLines:            40,
		MinTokens:           400,
		ExcludeDirs:         []string{".git", "vendor", "node_modules", "dist", "build", ".factory", "bin", "testdata"},
		ExcludeFileSuffixes: []string{"_test.go", ".pb.go", ".gen.go"},
		IgnoreGenerated:     true,
	}
}

// Occurrence represents a location where a duplicate block was found.
type Occurrence struct {
	Path      string
	StartLine int
	EndLine   int
}

// Finding represents a detected duplicate code block.
type Finding struct {
	// Fingerprint is the stable identifier for this duplicate block.
	// For display, it's truncated to 40 chars. For baseline comparison, use StableFingerprint.
	Fingerprint string
	// StableFingerprint is the full normalized fingerprint (not truncated).
	// Use this for baseline comparisons to ensure deterministic matching.
	StableFingerprint string
	TokenCount        int
	LineCount         int
	Occurrences       []Occurrence
}

// CheckRepo scans the repository for duplicate code and returns findings.
func CheckRepo(root string, cfg Config) ([]Finding, error) {
	if cfg.MinLines == 0 {
		cfg.MinLines = DefaultConfig().MinLines
	}
	if cfg.MinTokens == 0 {
		cfg.MinTokens = DefaultConfig().MinTokens
	}
	if cfg.ExcludeDirs == nil {
		cfg.ExcludeDirs = DefaultConfig().ExcludeDirs
	}
	if cfg.ExcludeFileSuffixes == nil {
		cfg.ExcludeFileSuffixes = DefaultConfig().ExcludeFileSuffixes
	}

	files, err := listGoFiles(root, cfg)
	if err != nil {
		return nil, err
	}

	// Normalize root to "." for consistent path handling
	normRoot := "."
	if root != "" && root != "." {
		normRoot = root
	}

	var allFiles []fileTokens
	for _, f := range files {
		ft, err := tokenizeFile(f)
		if err != nil {
			return nil, fmt.Errorf("tokenizing %s: %w", f, err)
		}
		// Normalize path to repo-relative for consistent coalescing
		normalizedPath := NormalizePathForBaseline(ft.path, normRoot)
		ft.path = normalizedPath
		allFiles = append(allFiles, ft)
	}

	// Track raw windows for coalescing
	windowMap := make(map[string][]rawWindow)
	fingerprintTokens := make(map[string]int)

	for i, ft1 := range allFiles {
		if len(ft1.tokens) < cfg.MinTokens {
			continue
		}
		for j := i + 1; j < len(allFiles); j++ {
			ft2 := allFiles[j]
			if len(ft2.tokens) < cfg.MinTokens {
				continue
			}
			findCommonWindows(ft1, ft2, cfg, windowMap, fingerprintTokens)
		}
	}

	// Coalesce overlapping windows into maximal clone findings
	coalesced := coalesceFindings(windowMap, fingerprintTokens)

	// Convert to Finding type
	var findings []Finding
	for _, cf := range coalesced {
		findings = append(findings, Finding{
			Fingerprint:       truncateFingerprint(cf.Fingerprint),
			StableFingerprint: cf.StableFingerprint,
			TokenCount:        cf.TokenCount,
			LineCount:         cf.LineCount,
			Occurrences:       cf.Occurrences,
		})
	}

	// Sort deterministically by stable fingerprint
	sort.Slice(findings, func(i, j int) bool {
		if findings[i].StableFingerprint != findings[j].StableFingerprint {
			return findings[i].StableFingerprint < findings[j].StableFingerprint
		}
		return false
	})

	return findings, nil
}

func findCommonWindows(ft1, ft2 fileTokens, cfg Config,
	windowMap map[string][]rawWindow,
	fingerprintTokens map[string]int) {

	fp1 := make(map[string][]int)
	for i := 0; i <= len(ft1.tokens)-cfg.MinTokens; i++ {
		window := ft1.tokens[i : i+cfg.MinTokens]
		fp := normalizeFingerprint(window)
		fp1[fp] = append(fp1[fp], i)
	}

	fp2 := make(map[string][]int)
	for i := 0; i <= len(ft2.tokens)-cfg.MinTokens; i++ {
		window := ft2.tokens[i : i+cfg.MinTokens]
		fp := normalizeFingerprint(window)
		fp2[fp] = append(fp2[fp], i)
	}

	// Sort fingerprints for deterministic processing
	var fps []string
	for fp := range fp1 {
		fps = append(fps, fp)
	}
	sort.Strings(fps)

	for _, fp := range fps {
		pos1 := fp1[fp]
		pos2, ok := fp2[fp]
		if !ok {
			continue
		}

		// Record token count once per fingerprint
		if _, exists := fingerprintTokens[fp]; !exists {
			fingerprintTokens[fp] = cfg.MinTokens
		}

		// Add raw windows for file 1
		for _, startPos := range pos1 {
			startLine := ft1.lines[startPos]
			endLine := ft1.lines[startPos+cfg.MinTokens-1]
			if endLine-startLine+1 >= cfg.MinLines {
				windowMap[fp] = append(windowMap[fp], rawWindow{
					Path:      ft1.path,
					StartLine: startLine,
					EndLine:   endLine,
					StartPos:  startPos,
					EndPos:    startPos + cfg.MinTokens - 1,
				})
			}
		}

		// Add raw windows for file 2
		for _, startPos := range pos2 {
			startLine := ft2.lines[startPos]
			endLine := ft2.lines[startPos+cfg.MinTokens-1]
			if endLine-startLine+1 >= cfg.MinLines {
				windowMap[fp] = append(windowMap[fp], rawWindow{
					Path:      ft2.path,
					StartLine: startLine,
					EndLine:   endLine,
					StartPos:  startPos,
					EndPos:    startPos + cfg.MinTokens - 1,
				})
			}
		}
	}
}

type fileTokens struct {
	path   string
	tokens []token.Token
	lines  []int
}

func listGoFiles(root string, cfg Config) ([]string, error) {
	var files []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return nil
		}
		for _, dir := range cfg.ExcludeDirs {
			if rel == dir || strings.HasPrefix(rel, dir+"/") {
				if info.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}
		}
		if info.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}
		for _, suffix := range cfg.ExcludeFileSuffixes {
			if strings.HasSuffix(path, suffix) {
				return nil
			}
		}
		if cfg.IgnoreGenerated && isGeneratedFile(path) {
			return nil
		}
		files = append(files, path)
		return nil
	})
	return files, err
}

// isGeneratedFile checks if a file has the canonical Go generated-file marker.
// Per cmd/go documentation, a file is considered generated if the marker
// appears before the first non-comment, non-blank line.
func isGeneratedFile(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		// First non-comment, non-blank line reached
		if strings.HasPrefix(trimmed, "//") {
			// It's a comment line - check if it's the generated marker
			if generatedMarker.MatchString(trimmed) {
				return true
			}
			// Not the marker, keep checking subsequent comment lines
			continue
		}
		// Not a comment line - stop scanning
		return false
	}
	return false
}

func tokenizeFile(path string) (fileTokens, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return fileTokens{}, fmt.Errorf("reading %s: %w", path, err)
	}
	fset := token.NewFileSet()
	file := fset.AddFile(path, fset.Base(), len(data))
	var s scanner.Scanner
	s.Init(file, data, nil, 0)
	var tokens []token.Token
	var lines []int
	for {
		pos, tok, _ := s.Scan()
		if tok == token.EOF {
			break
		}
		if tok == token.COMMENT {
			continue
		}
		tokens = append(tokens, tok)
		lines = append(lines, file.Line(pos))
	}
	return fileTokens{path: path, tokens: tokens, lines: lines}, nil
}

func normalizeFingerprint(tokens []token.Token) string {
	var buf bytes.Buffer
	for i, t := range tokens {
		switch t {
		case token.IDENT:
			buf.WriteString("IDENT")
		case token.STRING, token.CHAR:
			buf.WriteString("STRING")
		case token.INT, token.FLOAT, token.IMAG:
			buf.WriteString("NUMBER")
		default:
			buf.WriteString(t.String())
		}
		if i < len(tokens)-1 {
			buf.WriteByte(' ')
		}
	}
	return buf.String()
}

func truncateFingerprint(fp string) string {
	if len(fp) > 40 {
		return fp[:40] + "..."
	}
	return fp
}

func deduplicateOccurrences(occs []Occurrence) []Occurrence {
	if len(occs) < 2 {
		return occs
	}
	sort.Slice(occs, func(i, j int) bool {
		return occs[i].StartLine < occs[j].StartLine
	})
	var result []Occurrence
	current := occs[0]
	for i := 1; i < len(occs); i++ {
		next := occs[i]
		if next.StartLine <= current.EndLine+1 {
			if next.EndLine > current.EndLine {
				current.EndLine = next.EndLine
			}
		} else {
			result = append(result, current)
			current = next
		}
	}
	result = append(result, current)
	return result
}

// PrintFindings prints findings in human-readable format.
func PrintFindings(findings []Finding) {
	if len(findings) == 0 {
		fmt.Println("No duplicate code detected.")
		return
	}
	fmt.Printf("Found %d duplicate code blocks:\n\n", len(findings))
	for i, f := range findings {
		fmt.Printf("%d. Duplicate block (%d tokens, ~%d lines):\n", i+1, f.TokenCount, f.LineCount)
		for _, occ := range f.Occurrences {
			fmt.Printf("   - %s:%d-%d\n", occ.Path, occ.StartLine, occ.EndLine)
		}
		fmt.Println()
	}
}
