// Package dupcode provides duplicate code detection for Go source files.
package dupcode

import (
	"fmt"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// AlgorithmVersion is the version of the duplicate detection algorithm.
// Version 1: Sliding window detection with basic deduplication.
// Version 2: Sliding window detection with coalescing of overlapping windows
// Version 3: Deterministic maximal clone detection via aligned seed-match chaining.
// Version 4: Truthful maximal clone detection with content-based seed matching,
//
//	offset-independent chaining, and complete token fingerprinting.
//
// Algorithm v4 corrects v3 semantics:
// - Matches seeds by content, not absolute token position.
// - Chains across different seed fingerprints within the same clone body.
// - Generates occurrences from maximal token ranges, not individual seed windows.
// - Fingerprints the complete normalized token sequence for stable identity.
const AlgorithmVersion = 4

// generatedMarker matches the canonical Go generated-file marker format.
// Per cmd/go, matches lines like: "// Code generated by ... DO NOT EDIT."
var generatedMarker = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

// Config holds configuration for duplicate code detection.
type Config struct {
	Root                string
	MinLines            int
	MinTokens           int
	ExcludeDirs         []string
	ExcludeFileSuffixes []string
	IgnoreGenerated     bool
}

// DefaultConfig returns the default configuration.
// These thresholds are aligned with the gate policy of MinLines=40, MinTokens=400.
// The baseline + ratchet model allows these lower thresholds while tolerating
// existing historical duplication through the committed baseline.
func DefaultConfig() Config {
	return Config{
		MinLines:            40,
		MinTokens:           400,
		ExcludeDirs:         []string{".git", "vendor", "node_modules", "dist", "build", ".factory", "bin", "testdata"},
		ExcludeFileSuffixes: []string{"_test.go", ".pb.go", ".gen.go"},
		IgnoreGenerated:     true,
	}
}

// Occurrence represents a location where a duplicate block was found.
type Occurrence struct {
	Path      string
	StartLine int
	EndLine   int
}

// Finding represents a detected duplicate code block.
type Finding struct {
	// Fingerprint is the stable identifier for this duplicate block.
	// For display, it's truncated to 40 chars. For baseline comparison, use StableFingerprint.
	Fingerprint string
	// StableFingerprint is the full normalized fingerprint (not truncated).
	// Use this for baseline comparisons to ensure deterministic matching.
	StableFingerprint string
	TokenCount        int
	LineCount         int
	Occurrences       []Occurrence
}

// CheckRepo scans the repository for duplicate code and returns findings.
//
// CheckRepo builds the region-aware analysis map for every file and
// routes both the public production Finding projection and the
// internal exact-geometry assertions through the same production
// pipeline seam (v4BuildInternalFindings). The allAnalyses map is
// consumed by the shared seam; the final tree does NOT carry an
// unused production analysis map.
func CheckRepo(root string, cfg Config) ([]Finding, error) {
	if cfg.MinLines == 0 {
		cfg.MinLines = DefaultConfig().MinLines
	}
	if cfg.MinTokens == 0 {
		cfg.MinTokens = DefaultConfig().MinTokens
	}
	if cfg.ExcludeDirs == nil {
		cfg.ExcludeDirs = DefaultConfig().ExcludeDirs
	}
	if cfg.ExcludeFileSuffixes == nil {
		cfg.ExcludeFileSuffixes = DefaultConfig().ExcludeFileSuffixes
	}

	files, err := listGoFiles(root, cfg)
	if err != nil {
		return nil, err
	}

	// Normalize root to "." for consistent path handling
	normRoot := "."
	if root != "" && root != "." {
		normRoot = root
	}

	var allFiles []fileTokens
	var analyzedInventory []v4AnalyzedFile
	allAnalyses := make(map[string]*v4FileAnalysis)
	allAnalyzedFiles := make(map[string]*v4AnalyzedFile)
	for _, f := range files {
		analyzed, aerr := analyzeV4AnalyzedFile(f)
		if aerr != nil {
			return nil, fmt.Errorf("analysing %s: %w", f, aerr)
		}
		// Normalize every embedded region identity together with the file
		// token inventory so all downstream coordinates share one path.
		normalizedPath := NormalizePathForBaseline(analyzed.FileTokens.path, normRoot)
		rebaseV4AnalyzedFilePath(&analyzed, normalizedPath)
		allFiles = append(allFiles, analyzed.FileTokens)
		analyzedInventory = append(analyzedInventory, analyzed)
	}
	// Take pointers only after the inventory slice is complete; pointers into
	// a growing loop-local value would otherwise alias a later file.
	for i := range analyzedInventory {
		path := analyzedInventory[i].FileTokens.path
		allAnalyses[path] = &analyzedInventory[i].Analysis
		allAnalyzedFiles[path] = &analyzedInventory[i]
	}

	// Track raw windows for coalescing
	windowMap := make(map[string][]rawWindow)
	fingerprintTokens := make(map[string]int)

	for i, ft1 := range allFiles {
		if len(ft1.tokens) < cfg.MinTokens {
			continue
		}
		for j := i + 1; j < len(allFiles); j++ {
			ft2 := allFiles[j]
			if len(ft2.tokens) < cfg.MinTokens {
				continue
			}
			findCommonWindows(ft1, ft2, cfg, windowMap, fingerprintTokens)
		}
	}

	// Shared production seam (P0 correction 10). The same internal
	// pipeline produces the public Finding projection.
	internal, err := v4BuildInternalFindingsChecked(windowMap, allAnalyses, allAnalyzedFiles)
	if err != nil {
		return nil, err
	}

	// Convert to Finding type
	var findings []Finding
	for _, f := range internal {
		findings = append(findings, Finding{
			Fingerprint:       truncateFingerprint(f.StableFingerprint),
			StableFingerprint: f.StableFingerprint,
			TokenCount:        f.TokenCount,
			LineCount:         f.LineCount,
			Occurrences:       convertOccurrences(f.Occurrences),
		})
	}

	// The checked shared seam returns canonical total order; projection must
	// not introduce a second, weaker sort.
	return findings, nil
}

type fileTokens struct {
	path   string
	tokens []token.Token
	lines  []int
}

func listGoFiles(root string, cfg Config) ([]string, error) {
	var files []string
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return nil
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return nil
		}
		for _, dir := range cfg.ExcludeDirs {
			if rel == dir || strings.HasPrefix(rel, dir+"/") {
				if info.IsDir() {
					return filepath.SkipDir
				}
				return nil
			}
		}
		if info.IsDir() || !strings.HasSuffix(path, ".go") {
			return nil
		}
		for _, suffix := range cfg.ExcludeFileSuffixes {
			if strings.HasSuffix(path, suffix) {
				return nil
			}
		}
		if cfg.IgnoreGenerated && isGeneratedFile(path) {
			return nil
		}
		files = append(files, path)
		return nil
	})
	return files, err
}

// isGeneratedFile checks if a file has the canonical Go generated-file marker.
// Per cmd/go documentation, a file is considered generated if the marker
// appears before the first non-comment, non-blank line.
func isGeneratedFile(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	lines := strings.Split(string(data), "\n")
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		// First non-comment, non-blank line reached
		if strings.HasPrefix(trimmed, "//") {
			// It's a comment line - check if it's the generated marker
			if generatedMarker.MatchString(trimmed) {
				return true
			}
			// Not the marker, keep checking subsequent comment lines
			continue
		}
		// Not a comment line - stop scanning
		return false
	}
	return false
}
